// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unitask.Infrastructure.Persistence;

#nullable disable

namespace Unitask.Infrastructure.Migrations
{
    [DbContext(typeof(UnitaskDbContext))]
    partial class UnitaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unitask.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__Activity__3214EC072A4CA5A1");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_activity_created_at");

                    b.HasIndex(new[] { "UserId" }, "idx_activity_user");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.AdminReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionTaken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReportedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id")
                        .HasName("PK__AdminRep__3214EC0735BD4C61");

                    b.HasIndex("ReportedById");

                    b.HasIndex("ReportedJobId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_report_created_at");

                    b.HasIndex(new[] { "Status" }, "idx_report_status");

                    b.ToTable("AdminReports");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("draft");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__BlogPost__3214EC072AC3FACF");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "Slug" }, "UQ__BlogPost__BC7B5FB6BEECFCA5")
                        .IsUnique();

                    b.HasIndex(new[] { "PublishedAt" }, "idx_blog_published_at");

                    b.HasIndex(new[] { "Slug" }, "idx_blog_slug");

                    b.HasIndex(new[] { "Status" }, "idx_blog_status");

                    b.ToTable("BlogPosts", t =>
                        {
                            t.HasTrigger("trg_BlogPosts_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BusinessDashboardView", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CompletedProjects")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Industry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("OpenJobs")
                        .HasColumnType("integer");

                    b.Property<int?>("PendingApplications")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal?>("TotalSpent")
                        .HasColumnType("decimal(15, 2)");

                    b.ToTable((string)null);

                    b.ToView("BusinessDashboardView", (string)null);
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("BusinessLicenseUrl")
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompanySize")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("startup");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CompletedProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("IsPostingLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("RejectionStrikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC07C9C76523");

                    b.HasIndex(new[] { "UserId" }, "UQ__Business__1788CC4DAC86ABAD")
                        .IsUnique();

                    b.HasIndex(new[] { "Industry" }, "idx_business_industry");

                    b.HasIndex(new[] { "IsVerified" }, "idx_business_verified");

                    b.ToTable("BusinessProfiles", t =>
                        {
                            t.HasTrigger("trg_BusinessProfiles_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IssuingOrganization")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StudentId" }, "idx_certification_student");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<decimal>("FinalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BusinessId" }, "idx_contract_business");

                    b.HasIndex(new[] { "JobId" }, "idx_contract_job");

                    b.HasIndex(new[] { "Status" }, "idx_contract_status");

                    b.HasIndex(new[] { "StudentId" }, "idx_contract_student");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__Conversa__3214EC07003DAE44");

                    b.HasIndex("User2Id");

                    b.HasIndex(new[] { "User1Id", "User2Id" }, "idx_conversation_users");

                    b.ToTable("Conversations", t =>
                        {
                            t.HasTrigger("trg_Conversations_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AppealDeadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text");

                    b.Property<Guid?>("MediatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NEGOTIATION");

                    b.Property<int?>("StudentPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MilestoneId" }, "idx_dispute_milestone");

                    b.HasIndex(new[] { "Status" }, "idx_dispute_status");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Degree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StudentId" }, "idx_education_student");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<int?>("HelpfulCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__FAQs__3214EC07403668E9");

                    b.HasIndex(new[] { "Category" }, "idx_faq_category");

                    b.HasIndex(new[] { "OrderIndex" }, "idx_faq_order");

                    b.ToTable("FAQs", t =>
                        {
                            t.HasTrigger("trg_FAQs_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("DurationType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("micro");

                    b.Property<string>("ExperienceLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("beginner");

                    b.Property<bool?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsRemote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequiredSkillsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("SpotsFilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("SpotsTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("open");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id")
                        .HasName("PK__Jobs__3214EC076D201E18");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Status", "BusinessId" }, "IX_Jobs_Status_BusinessId");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_Jobs_Status_CreatedAt");

                    b.HasIndex(new[] { "BusinessId" }, "idx_job_business");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_job_created_at");

                    b.HasIndex(new[] { "Deadline" }, "idx_job_deadline");

                    b.HasIndex(new[] { "IsFeatured" }, "idx_job_featured");

                    b.HasIndex(new[] { "Status" }, "idx_job_status");

                    b.ToTable("Jobs", t =>
                        {
                            t.HasTrigger("trg_Jobs_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedTimeline")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__JobAppli__3214EC078CD78FF4");

                    b.HasIndex(new[] { "JobId", "Status" }, "IX_JobApplications_JobId_Status");

                    b.HasIndex(new[] { "StudentId", "AppliedAt" }, "IX_JobApplications_StudentId_AppliedAt");

                    b.HasIndex(new[] { "JobId" }, "idx_application_job");

                    b.HasIndex(new[] { "Status" }, "idx_application_status");

                    b.HasIndex(new[] { "StudentId" }, "idx_application_student");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<int?>("JobCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__JobCateg__3214EC07850F645F");

                    b.HasIndex(new[] { "Slug" }, "UQ__JobCateg__BC7B5FB617A64871")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "idx_category_slug");

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobDetailsView", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("DurationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("SpotsFilled")
                        .HasColumnType("integer");

                    b.Property<int?>("SpotsTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("TotalApplications")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable((string)null);

                    b.ToView("JobDetailsView", (string)null);
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__Messages__3214EC07ECFE687E");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "IX_Messages_ConversationId_CreatedAt");

                    b.HasIndex(new[] { "ConversationId", "IsRead", "SenderId" }, "IX_Messages_Unread");

                    b.HasIndex(new[] { "ConversationId" }, "idx_message_conversation");

                    b.HasIndex(new[] { "IsRead" }, "idx_message_is_read");

                    b.HasIndex(new[] { "SenderId" }, "idx_message_sender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.MessageFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MessageFlags");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EscrowedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContractId" }, "idx_milestone_contract");

                    b.HasIndex(new[] { "Status" }, "idx_milestone_status");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RelatedJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC077F7DF681");

                    b.HasIndex("RelatedJobId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "IX_Notifications_UserId_IsRead_CreatedAt");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_notification_created_at");

                    b.HasIndex(new[] { "IsRead" }, "idx_notification_is_read");

                    b.HasIndex(new[] { "UserId" }, "idx_notification_user");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07BD9B1F00");

                    b.HasIndex("BusinessId");

                    b.HasIndex("JobId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "JobApplicationId" }, "idx_payment_application");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_payment_created_at");

                    b.HasIndex(new[] { "Status" }, "idx_payment_status");

                    b.ToTable("Payments", t =>
                        {
                            t.HasTrigger("trg_Payments_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.PortfolioProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsHighlighted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StudentId" }, "idx_portfolio_student");

                    b.HasIndex(new[] { "StudentId", "SortOrder" }, "idx_portfolio_student_order");

                    b.ToTable("PortfolioProjects");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SkillEndorsementsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3214EC07C82B75F3");

                    b.HasIndex("FromUserId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "ToUserId", "Rating" }, "IX_Reviews_ToUserId_Rating");

                    b.HasIndex(new[] { "Rating" }, "idx_review_rating");

                    b.HasIndex(new[] { "ToUserId" }, "idx_review_to_user");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasTrigger("trg_Reviews_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK__Skills__3214EC073C6B2BBB");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills__737584F68FA901A4")
                        .IsUnique();

                    b.HasIndex(new[] { "Category" }, "idx_skill_category");

                    b.HasIndex(new[] { "Name" }, "idx_skill_name");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentDashboardView", b =>
                {
                    b.Property<int?>("ActiveJobs")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("CompletedJobs")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PendingApplications")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalEarnings")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("University")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable((string)null);

                    b.ToView("StudentDashboardView", (string)null);
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CompletedJobs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("CvUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("GradePoint")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("text");

                    b.Property<string>("StudentCardUrl")
                        .HasColumnType("text");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TotalEarnings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("University")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC07261DB460");

                    b.HasIndex(new[] { "UserId" }, "UQ__StudentP__1788CC4D8B81EDAD")
                        .IsUnique();

                    b.HasIndex(new[] { "Major" }, "idx_student_major");

                    b.HasIndex(new[] { "University" }, "idx_student_university");

                    b.HasIndex(new[] { "IsVerified" }, "idx_student_verified");

                    b.ToTable("StudentProfiles", t =>
                        {
                            t.HasTrigger("trg_StudentProfiles_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<int?>("EndorsementCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Proficiency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("beginner");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__StudentS__3214EC076E534E1D");

                    b.HasIndex(new[] { "StudentId", "SkillId" }, "UQ__StudentS__5F3F22803C6777EE")
                        .IsUnique();

                    b.HasIndex(new[] { "SkillId" }, "idx_student_skill_skill");

                    b.HasIndex(new[] { "StudentId" }, "idx_student_skill_student");

                    b.ToTable("StudentSkills");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TotalWithdrawn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("Id")
                        .HasName("PK__StudentW__3214EC07C3EEA6EB");

                    b.HasIndex(new[] { "StudentId" }, "UQ__StudentW__32C52B980C342C3B")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "idx_wallet_student");

                    b.ToTable("StudentWallets");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientEvidenceUrl")
                        .HasColumnType("text");

                    b.Property<string>("ClientFeedback")
                        .HasColumnType("text");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MilestoneId" }, "idx_submission_milestone");

                    b.HasIndex(new[] { "StudentId" }, "idx_submission_student");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("student");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC076B717E97");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534FF2A9ABE")
                        .IsUnique();

                    b.HasIndex(new[] { "CreatedAt" }, "idx_users_created_at");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "UserType" }, "idx_users_user_type");

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_Users_UpdatedAt");
                        });
                });

            modelBuilder.Entity("Unitask.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK__Withdraw__3214EC07A06B1D8F");

                    b.HasIndex(new[] { "Status" }, "idx_withdrawal_status");

                    b.HasIndex(new[] { "StudentId" }, "idx_withdrawal_student");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ActivityL__UserI__367C1819");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.AdminReport", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "ReportedBy")
                        .WithMany("AdminReportReportedBies")
                        .HasForeignKey("ReportedById")
                        .IsRequired()
                        .HasConstraintName("FK__AdminRepo__Repor__1975C517");

                    b.HasOne("Unitask.Domain.Entities.Job", "ReportedJob")
                        .WithMany("AdminReports")
                        .HasForeignKey("ReportedJobId")
                        .HasConstraintName("FK__AdminRepo__Repor__1B5E0D89");

                    b.HasOne("Unitask.Domain.Entities.User", "ReportedUser")
                        .WithMany("AdminReportReportedUsers")
                        .HasForeignKey("ReportedUserId")
                        .HasConstraintName("FK__AdminRepo__Repor__1A69E950");

                    b.Navigation("ReportedBy");

                    b.Navigation("ReportedJob");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BlogPost", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__BlogPosts__Autho__24285DB4");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BusinessProfile", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "User")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("Unitask.Domain.Entities.BusinessProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BusinessP__UserI__5441852A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Certification", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("Certifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.BusinessProfile", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unitask.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "User1")
                        .WithMany("ConversationUser1s")
                        .HasForeignKey("User1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__User1__29E1370A");

                    b.HasOne("Unitask.Domain.Entities.User", "User2")
                        .WithMany("ConversationUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__User2__2AD55B43");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Dispute", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Education", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("Educations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Job", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("Jobs")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Jobs__BusinessId__6A30C649");

                    b.HasOne("Unitask.Domain.Entities.JobCategory", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Jobs__CategoryId__6B24EA82");

                    b.Navigation("Business");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__JobId__0697FACD");

                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("JobApplications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__Stude__078C1F06");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Message", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Conver__308E3499");

                    b.HasOne("Unitask.Domain.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Sender__318258D2");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Contract", "Contract")
                        .WithMany("Milestones")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Job", "RelatedJob")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedJobId")
                        .HasConstraintName("FK__Notificat__Relat__11D4A34F");

                    b.HasOne("Unitask.Domain.Entities.User", "RelatedUser")
                        .WithMany("NotificationRelatedUsers")
                        .HasForeignKey("RelatedUserId")
                        .HasConstraintName("FK__Notificat__Relat__12C8C788");

                    b.HasOne("Unitask.Domain.Entities.User", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__10E07F16");

                    b.Navigation("RelatedJob");

                    b.Navigation("RelatedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("Payments")
                        .HasForeignKey("BusinessId")
                        .HasConstraintName("FK__Payments__Busine__7FB5F314");

                    b.HasOne("Unitask.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("Payments")
                        .HasForeignKey("JobApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__JobApp__7EC1CEDB");

                    b.HasOne("Unitask.Domain.Entities.Job", "Job")
                        .WithMany("Payments")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK__Payments__JobId__7DCDAAA2");

                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Payments__Studen__00AA174D");

                    b.Navigation("Business");

                    b.Navigation("Job");

                    b.Navigation("JobApplication");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.PortfolioProject", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("PortfolioProjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Review", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "FromUser")
                        .WithMany("ReviewFromUsers")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__FromUse__0A338187");

                    b.HasOne("Unitask.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("Reviews")
                        .HasForeignKey("JobApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__JobAppl__093F5D4E");

                    b.HasOne("Unitask.Domain.Entities.Job", "Job")
                        .WithMany("Reviews")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__JobId__084B3915");

                    b.HasOne("Unitask.Domain.Entities.User", "ToUser")
                        .WithMany("ReviewToUsers")
                        .HasForeignKey("ToUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__ToUserI__0B27A5C0");

                    b.Navigation("FromUser");

                    b.Navigation("Job");

                    b.Navigation("JobApplication");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Unitask.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentPr__UserI__47DBAE45");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentSkill", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentSk__Skill__19DFD96B");

                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentSk__Stude__18EBB532");

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentWallet", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithOne("StudentWallet")
                        .HasForeignKey("Unitask.Domain.Entities.StudentWallet", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentWa__Stude__7B5B524B");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.Milestone", "Milestone")
                        .WithMany("Submissions")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.HasOne("Unitask.Domain.Entities.StudentProfile", "Student")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Withdrawa__Stude__0B91BA14");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.BusinessProfile", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Job", b =>
                {
                    b.Navigation("AdminReports");

                    b.Navigation("JobApplications");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Milestone", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.Skill", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("JobApplications");

                    b.Navigation("Payments");

                    b.Navigation("PortfolioProjects");

                    b.Navigation("StudentSkills");

                    b.Navigation("StudentWallet");

                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("Unitask.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AdminReportReportedBies");

                    b.Navigation("AdminReportReportedUsers");

                    b.Navigation("BlogPosts");

                    b.Navigation("BusinessProfile");

                    b.Navigation("ConversationUser1s");

                    b.Navigation("ConversationUser2s");

                    b.Navigation("Messages");

                    b.Navigation("NotificationRelatedUsers");

                    b.Navigation("NotificationUsers");

                    b.Navigation("ReviewFromUsers");

                    b.Navigation("ReviewToUsers");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
